//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Win10\source\repos\BNFCTest\ANTLR Test\Spreadsheet.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ANTLR_Test {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SpreadsheetParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ISpreadsheetListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SpreadsheetParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] SpreadsheetParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpreadsheetParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] SpreadsheetParser.CompileUnitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SpreadsheetParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStm([NotNull] SpreadsheetParser.StmContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpreadsheetParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStm([NotNull] SpreadsheetParser.StmContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SpreadsheetParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] SpreadsheetParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpreadsheetParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] SpreadsheetParser.ExpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SpreadsheetParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] SpreadsheetParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpreadsheetParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] SpreadsheetParser.ValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SpreadsheetParser.aexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexp([NotNull] SpreadsheetParser.AexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SpreadsheetParser.aexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexp([NotNull] SpreadsheetParser.AexpContext context);
}
} // namespace ANTLR_Test
